name: Deploy to production
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  clone-latest:
    runs-on: self-hosted
    steps:
      - run: cd /home/ubuntu/line-22
      - run: git pull 
