name: Deploy to production
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  clone-latest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: sudo systemctl reload nginx
